const employees = [
    {
        id: 1,
        firstName: "Amit",
        lastName: "Sharma",
        empId: "EMP1001",
        role: "Employee",
        email: "amit.sharma@example.com",
        department: "Engineering",
        designation: "Frontend Developer",
        dateOfJoining: "2023-05-10",
        password: "1234",
        tasks: [
            {
                taskId: "emp1-task1",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Design Homepage UI",
                description:
                    "Create wireframes and initial design for homepage",
                date: "2025-09-10",
                category: "Design",
                taskPriority: "High",
            },
            {
                taskId: "emp1-task2",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Setup GitHub Repo",
                description: "Initialize repo and push base code",
                date: "2025-09-05",
                category: "Development",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 1,
            completedTasks: 1,
            failedTasks: 0,
            newTasks: 0,
        },
    },
    {
        id: 2,
        firstName: "Neha",
        lastName: "Verma",
        empId: "EMP1002",
        role: "Employee",
        email: "neha.verma@example.com",
        department: "Engineering",
        designation: "Backend Developer",
        dateOfJoining: "2023-06-15",
        password: "1234",
        tasks: [
            {
                taskId: "emp2-task1",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Prepare API Documentation",
                description:
                    "Write documentation for user authentication endpoints",
                date: "2025-09-12",
                category: "Documentation",
                taskPriority: "High",
            },
            {
                taskId: "emp2-task2",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Write Unit Tests",
                description: "Add tests for authentication services",
                date: "2025-09-16",
                category: "Testing",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 1,
            completedTasks: 0,
            failedTasks: 0,
            newTasks: 1,
        },
    },
    {
        id: 3,
        firstName: "Ramesh",
        lastName: "Kumar",
        empId: "EMP1003",
        role: "Employee",
        email: "ramesh.kumar@example.com",
        department: "Database",
        designation: "Database Engineer",
        dateOfJoining: "2023-07-20",
        password: "1234",
        tasks: [
            {
                taskId: "emp3-task1",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Database Schema",
                description: "Design schema for employee and task management",
                date: "2025-09-15",
                category: "Database",
                taskPriority: "High",
            },
            {
                taskId: "emp3-task2",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Optimize Queries",
                description: "Improve database query performance",
                date: "2025-09-18",
                category: "Database",
                taskPriority: "High",
            },
        ],
        taskSummary: {
            activeTasks: 1,
            completedTasks: 0,
            failedTasks: 0,
            newTasks: 1,
        },
    },
    {
        id: 4,
        firstName: "Priya",
        lastName: "Singh",
        empId: "EMP1004",
        role: "Employee",
        email: "priya.singh@example.com",
        department: "Frontend",
        designation: "UI/UX Designer",
        dateOfJoining: "2023-08-01",
        password: "1234",
        tasks: [
            {
                taskId: "emp4-task1",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Create Landing Page",
                description: "Develop landing page using React and Tailwind",
                date: "2025-09-02",
                category: "Frontend",
                taskPriority: "High",
            },
            {
                taskId: "emp4-task2",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Style Dashboard",
                description: "Apply Tailwind CSS styles to dashboard",
                date: "2025-09-13",
                category: "Frontend",
                taskPriority: "High",
            },
        ],
        taskSummary: {
            activeTasks: 1,
            completedTasks: 1,
            failedTasks: 0,
            newTasks: 0,
        },
    },
];

const admins = [
    {
        id: 101,
        firstName: "Mahesh",
        lastName: "Patel",
        empId: "ADM1001",
        role: "Admin",
        email: "admin1@example.com",
        department: "Management",
        designation: "Project Manager",
        dateOfJoining: "2022-04-10",
        password: "1234",
    },
];

export const setLocalStorage = () => {
    localStorage.setItem("employees", JSON.stringify(employees));
    localStorage.setItem("admins", JSON.stringify(admins));
};

export const getLocalStorage = () => {
    const employeesData = JSON.parse(localStorage.getItem("employees"));
    const adminsData = JSON.parse(localStorage.getItem("admins"));
    return { employeesData, adminsData };
};
