// const employees = [
//     {
//         id: 1,
//         firstName: "Amit",
//         email: "e@e.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Design Homepage UI",
//                 description:
//                     "Create wireframes and initial design for homepage",
//                 date: "2025-09-10",
//                 category: "Design",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Setup GitHub Repo",
//                 description: "Initialize repo and push base code",
//                 date: "2025-09-05",
//                 category: "Development",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Plan Dashboard Layout",
//                 description:
//                     "Create structure for admin and employee dashboards",
//                 date: "2025-09-21",
//                 category: "UI/UX",
//                 taskPriority: "Low",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Fix Login Validation",
//                 description: "Resolve validation error in login form",
//                 date: "2025-09-02",
//                 category: "Bugfix",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Implement Navbar",
//                 description: "Responsive navbar with Tailwind",
//                 date: "2025-09-14",
//                 category: "Frontend",
//                 taskPriority: "Medium",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 2,
//         firstName: "Neha",
//         email: "employee2@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Prepare API Documentation",
//                 description:
//                     "Write documentation for user authentication endpoints",
//                 date: "2025-09-12",
//                 category: "Documentation",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Fix Navbar Bug",
//                 description: "Resolve alignment issue in mobile view",
//                 date: "2025-09-03",
//                 category: "Bugfix",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Write Unit Tests",
//                 description: "Add tests for authentication services",
//                 date: "2025-09-16",
//                 category: "Testing",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Create API Endpoints",
//                 description: "Develop endpoints for employee management",
//                 date: "2025-09-01",
//                 category: "Backend",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Update Project README",
//                 description: "Add setup steps and usage guide",
//                 date: "2025-09-11",
//                 category: "Documentation",
//                 taskPriority: "Low",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 3,
//         firstName: "Ramesh",
//         email: "employee3@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Database Schema",
//                 description: "Design schema for employee and task management",
//                 date: "2025-09-15",
//                 category: "Database",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Optimize Queries",
//                 description: "Improve database query performance",
//                 date: "2025-09-18",
//                 category: "Database",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Backup Database",
//                 description: "Setup automated backup script",
//                 date: "2025-09-06",
//                 category: "Database",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Configure DB Replication",
//                 description: "Setup master-slave replication",
//                 date: "2025-09-04",
//                 category: "Database",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Add Indexes",
//                 description: "Index frequently used columns",
//                 date: "2025-09-19",
//                 category: "Database",
//                 taskPriority: "Medium",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 4,
//         firstName: "Priya",
//         email: "employee4@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Create Landing Page",
//                 description: "Develop landing page using React and Tailwind",
//                 date: "2025-09-02",
//                 category: "Frontend",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Implement Footer",
//                 description: "Add responsive footer with links",
//                 date: "2025-09-22",
//                 category: "Frontend",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Style Dashboard",
//                 description: "Apply Tailwind CSS styles to dashboard",
//                 date: "2025-09-13",
//                 category: "Frontend",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Cross-Browser Testing",
//                 description: "Fix layout issues in Safari",
//                 date: "2025-09-07",
//                 category: "Testing",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Hero Section",
//                 description: "Create hero banner with CTA",
//                 date: "2025-09-09",
//                 category: "Frontend",
//                 taskPriority: "Medium",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 1,
//             completedTasks: 2,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 5,
//         firstName: "Krishna",
//         email: "employee5@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Unit Testing",
//                 description: "Write unit tests for task creation module",
//                 date: "2025-09-20",
//                 category: "Testing",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Integration Testing",
//                 description: "Test integration of login and signup modules",
//                 date: "2025-09-12",
//                 category: "Testing",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Fix Failing Tests",
//                 description: "Resolve issues in Jest test suite",
//                 date: "2025-09-05",
//                 category: "Testing",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Mock APIs",
//                 description: "Setup mock API for frontend testing",
//                 date: "2025-09-08",
//                 category: "Testing",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Regression Testing",
//                 description: "Run regression suite after new release",
//                 date: "2025-09-17",
//                 category: "Testing",
//                 taskPriority: "High",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 6,
//         firstName: "Ganesh",
//         email: "employee6@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Organize Team Meeting",
//                 description: "Schedule and prepare agenda for weekly sync-up",
//                 date: "2025-09-08",
//                 category: "Management",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Book Conference Room",
//                 description: "Reserve room for client presentation",
//                 date: "2025-09-01",
//                 category: "Operations",
//                 taskPriority: "Low",
//             },
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Plan Team Outing",
//                 description: "Organize quarterly team-building outing",
//                 date: "2025-09-19",
//                 category: "Management",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Client Call Follow-up",
//                 description: "Missed follow-up with client",
//                 date: "2025-09-04",
//                 category: "Management",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Update Team Goals",
//                 description: "Revise goals for upcoming sprint",
//                 date: "2025-09-16",
//                 category: "Management",
//                 taskPriority: "Medium",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
//     {
//         id: 7,
//         firstName: "Gopal",
//         email: "employee7@example.com",
//         password: "1234",
//         tasks: [
//             {
//                 active: false,
//                 newTask: true,
//                 completed: false,
//                 failed: false,
//                 title: "Prepare Budget Report",
//                 description: "Draft Q3 financial report for review",
//                 date: "2025-09-18",
//                 category: "Finance",
//                 taskPriority: "High",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: false,
//                 failed: true,
//                 title: "Social Media Campaign",
//                 description: "Launch marketing posts for product release",
//                 date: "2025-09-04",
//                 category: "Marketing",
//                 taskPriority: "High",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Update Excel Sheets",
//                 description: "Track employee salaries and bonuses",
//                 date: "2025-09-11",
//                 category: "Finance",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: false,
//                 newTask: false,
//                 completed: true,
//                 failed: false,
//                 title: "Ad Campaign Report",
//                 description: "Summarize social media ad results",
//                 date: "2025-09-07",
//                 category: "Marketing",
//                 taskPriority: "Medium",
//             },
//             {
//                 active: true,
//                 newTask: false,
//                 completed: false,
//                 failed: false,
//                 title: "Plan Investment Strategy",
//                 description: "Research for long-term investment options",
//                 date: "2025-09-20",
//                 category: "Finance",
//                 taskPriority: "High",
//             },
//         ],
//         taskSummary: {
//             activeTasks: 2,
//             completedTasks: 1,
//             failedTasks: 1,
//             newTasks: 1,
//         },
//     },
// ];

const employees = [
    {
        id: 1,
        firstName: "Amit",
        email: "e@e.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp1-task1",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Design Homepage UI",
                description:
                    "Create wireframes and initial design for homepage",
                date: "2025-09-10",
                category: "Design",
                taskPriority: "High",
            },
            {
                taskId: "emp1-task2",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Setup GitHub Repo",
                description: "Initialize repo and push base code",
                date: "2025-09-05",
                category: "Development",
                taskPriority: "Medium",
            },
            {
                taskId: "emp1-task3",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Plan Dashboard Layout",
                description:
                    "Create structure for admin and employee dashboards",
                date: "2025-09-21",
                category: "UI/UX",
                taskPriority: "Low",
            },
            {
                taskId: "emp1-task4",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Fix Login Validation",
                description: "Resolve validation error in login form",
                date: "2025-09-02",
                category: "Bugfix",
                taskPriority: "High",
            },
            {
                taskId: "emp1-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Implement Navbar",
                description: "Responsive navbar with Tailwind",
                date: "2025-09-14",
                category: "Frontend",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 2,
        firstName: "Neha",
        email: "employee2@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp2-task1",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Prepare API Documentation",
                description:
                    "Write documentation for user authentication endpoints",
                date: "2025-09-12",
                category: "Documentation",
                taskPriority: "High",
            },
            {
                taskId: "emp2-task2",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Fix Navbar Bug",
                description: "Resolve alignment issue in mobile view",
                date: "2025-09-03",
                category: "Bugfix",
                taskPriority: "High",
            },
            {
                taskId: "emp2-task3",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Write Unit Tests",
                description: "Add tests for authentication services",
                date: "2025-09-16",
                category: "Testing",
                taskPriority: "Medium",
            },
            {
                taskId: "emp2-task4",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Create API Endpoints",
                description: "Develop endpoints for employee management",
                date: "2025-09-01",
                category: "Backend",
                taskPriority: "High",
            },
            {
                taskId: "emp2-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Update Project README",
                description: "Add setup steps and usage guide",
                date: "2025-09-11",
                category: "Documentation",
                taskPriority: "Low",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 3,
        firstName: "Ramesh",
        email: "employee3@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp3-task1",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Database Schema",
                description: "Design schema for employee and task management",
                date: "2025-09-15",
                category: "Database",
                taskPriority: "High",
            },
            {
                taskId: "emp3-task2",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Optimize Queries",
                description: "Improve database query performance",
                date: "2025-09-18",
                category: "Database",
                taskPriority: "High",
            },
            {
                taskId: "emp3-task3",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Backup Database",
                description: "Setup automated backup script",
                date: "2025-09-06",
                category: "Database",
                taskPriority: "Medium",
            },
            {
                taskId: "emp3-task4",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Configure DB Replication",
                description: "Setup master-slave replication",
                date: "2025-09-04",
                category: "Database",
                taskPriority: "High",
            },
            {
                taskId: "emp3-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Add Indexes",
                description: "Index frequently used columns",
                date: "2025-09-19",
                category: "Database",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 4,
        firstName: "Priya",
        email: "employee4@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp4-task1",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Create Landing Page",
                description: "Develop landing page using React and Tailwind",
                date: "2025-09-02",
                category: "Frontend",
                taskPriority: "High",
            },
            {
                taskId: "emp4-task2",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Implement Footer",
                description: "Add responsive footer with links",
                date: "2025-09-22",
                category: "Frontend",
                taskPriority: "Medium",
            },
            {
                taskId: "emp4-task3",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Style Dashboard",
                description: "Apply Tailwind CSS styles to dashboard",
                date: "2025-09-13",
                category: "Frontend",
                taskPriority: "High",
            },
            {
                taskId: "emp4-task4",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Cross-Browser Testing",
                description: "Fix layout issues in Safari",
                date: "2025-09-07",
                category: "Testing",
                taskPriority: "High",
            },
            {
                taskId: "emp4-task5",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Hero Section",
                description: "Create hero banner with CTA",
                date: "2025-09-09",
                category: "Frontend",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 1,
            completedTasks: 2,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 5,
        firstName: "Krishna",
        email: "employee5@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp5-task1",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Unit Testing",
                description: "Write unit tests for task creation module",
                date: "2025-09-20",
                category: "Testing",
                taskPriority: "High",
            },
            {
                taskId: "emp5-task2",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Integration Testing",
                description: "Test integration of login and signup modules",
                date: "2025-09-12",
                category: "Testing",
                taskPriority: "High",
            },
            {
                taskId: "emp5-task3",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Fix Failing Tests",
                description: "Resolve issues in Jest test suite",
                date: "2025-09-05",
                category: "Testing",
                taskPriority: "Medium",
            },
            {
                taskId: "emp5-task4",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Mock APIs",
                description: "Setup mock API for frontend testing",
                date: "2025-09-08",
                category: "Testing",
                taskPriority: "Medium",
            },
            {
                taskId: "emp5-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Regression Testing",
                description: "Run regression suite after new release",
                date: "2025-09-17",
                category: "Testing",
                taskPriority: "High",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 6,
        firstName: "Ganesh",
        email: "employee6@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp6-task1",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Organize Team Meeting",
                description: "Schedule and prepare agenda for weekly sync-up",
                date: "2025-09-08",
                category: "Management",
                taskPriority: "High",
            },
            {
                taskId: "emp6-task2",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Book Conference Room",
                description: "Reserve room for client presentation",
                date: "2025-09-01",
                category: "Operations",
                taskPriority: "Low",
            },
            {
                taskId: "emp6-task3",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Plan Team Outing",
                description: "Organize quarterly team-building outing",
                date: "2025-09-19",
                category: "Management",
                taskPriority: "Medium",
            },
            {
                taskId: "emp6-task4",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Client Call Follow-up",
                description: "Missed follow-up with client",
                date: "2025-09-04",
                category: "Management",
                taskPriority: "High",
            },
            {
                taskId: "emp6-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Update Team Goals",
                description: "Revise goals for upcoming sprint",
                date: "2025-09-16",
                category: "Management",
                taskPriority: "Medium",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
    {
        id: 7,
        firstName: "Gopal",
        email: "employee7@example.com",
        password: "1234",
        tasks: [
            {
                taskId: "emp7-task1",
                active: false,
                newTask: true,
                completed: false,
                failed: false,
                title: "Prepare Budget Report",
                description: "Draft Q3 financial report for review",
                date: "2025-09-18",
                category: "Finance",
                taskPriority: "High",
            },
            {
                taskId: "emp7-task2",
                active: false,
                newTask: false,
                completed: false,
                failed: true,
                title: "Social Media Campaign",
                description: "Launch marketing posts for product release",
                date: "2025-09-04",
                category: "Marketing",
                taskPriority: "High",
            },
            {
                taskId: "emp7-task3",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Update Excel Sheets",
                description: "Track employee salaries and bonuses",
                date: "2025-09-11",
                category: "Finance",
                taskPriority: "Medium",
            },
            {
                taskId: "emp7-task4",
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                title: "Ad Campaign Report",
                description: "Summarize social media ad results",
                date: "2025-09-07",
                category: "Marketing",
                taskPriority: "Medium",
            },
            {
                taskId: "emp7-task5",
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                title: "Plan Investment Strategy",
                description: "Research for long-term investment options",
                date: "2025-09-20",
                category: "Finance",
                taskPriority: "High",
            },
        ],
        taskSummary: {
            activeTasks: 2,
            completedTasks: 1,
            failedTasks: 1,
            newTasks: 1,
        },
    },
];

const admins = [
    {
        id: 101,
        firstName: "mahesh",
        email: "admin@example.com",
        password: "1234",
    },
];

export const setLocalStorage = () => {
    localStorage.setItem("employees", JSON.stringify(employees));
    localStorage.setItem("admins", JSON.stringify(admins));
};

export const getLocalStorage = () => {
    const employeesData = JSON.parse(localStorage.getItem("employees"));
    const adminsData = JSON.parse(localStorage.getItem("admins"));
    return { employeesData, adminsData };
};
